# Generated by Django 5.1.1 on 2024-12-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashcourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashcourse',
            name='resources',
            field=models.TextField(default='resources'),
            preserve_default=False,
        ),
    ]
