# Generated by Django 5.1.1 on 2024-12-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashcourse', '0002_crashcourse_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashcourse',
            name='generator_uuid',
            field=models.CharField(default='48b09b22-7efc-498a-9010-cc026ffcab93', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crashcourse',
            name='nav_summary',
            field=models.CharField(default='new crashcourse', max_length=100),
        ),
    ]
