# Generated by Django 5.1.4 on 2025-01-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('generator_uuid', models.CharField(max_length=200)),
                ('nav_summary', models.CharField(max_length=100)),
            ],
        ),
    ]
