# Generated by Django 5.1.1 on 2024-12-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='generator_uuid',
            field=models.CharField(default='48b09b22-7efc-498a-9010-cc026ffcab93', max_length=200),
            preserve_default=False,
        ),
    ]
