# Generated by Django 5.1.1 on 2024-12-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicetest', '0002_practicetest_generator_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='nav_summary',
            field=models.CharField(default='nav summary', max_length=100),
            preserve_default=False,
        ),
    ]
